name: Build and Deploy AssignmentTracker
on:
  push:
    branches:
      - main
jobs:
  Testing:
    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      TEST_DATABASE_HOST: ${{secrets.TEST_DATABASE_HOST}}
      TEST_DATABASE_USERNAME: ${{secrets.TEST_DATABASE_USERNAME}}
      TEST_DATABASE_PASSWORD: ${{secrets.TEST_DATABASE_PASSWORD}}
      TEST_DATABASE_NAME: ${{secrets.TEST_DATABASE_NAME}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.TEST_DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.TEST_DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest tests -s -v
      - name: Check tests passed
        if: ${{ failure() }}
        run: |
          echo "Tests failed. Cancelling deployment."
          exit 1
